openapi: 3.2.0
info:
  version: 2.0.0
  title: Oden Product Mappings API
  contact:
    name: Oden Support
    email: support@oden.io
    url: https://oden.io/contact/
  description: The Oden Private Partner API exposes RESTful API endpoints for clients to get, create and update data on the Oden Platform.
servers:
- url: https://api.oden.app
  description: Oden API server
security:
- APIKeyAuth: []
tags:
- name: Product Mappings
paths:
  /v2/product_mapping/search:
    post:
      operationId: search_product_mappings
      summary: Search product-to-line mappings
      tags:
      - Product Mappings
      description: 'Searches for Product Mappings.


        May be used to confirm a Product Mapping exists.


        Much like `product/search`, may be used to get `name`s of line or product from `id`s,

        or `id`s from `name`s.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductMapping'
            examples:
              match by product ID and line ID:
                summary: Match product mapping with given product and line ID.
                value:
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  product:
                    id: b5da7b1f-3c16-5084-a5da-95b2eba5a4db
              match by product name and line name+factory:
                summary: Match product mapping with given product and line name  - alternative example.
                value:
                  line:
                    name: Line 01
                    factory:
                      id: e32d004e-ce8b-40bf-bbc1-14fd907d2f47
                  product:
                    name: 2AFBCA5E
              match all by line:
                summary: Match all product mappings for a given line
                value:
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  match: all
      responses:
        '200':
          description: A list of product mappings.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductMapping'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
  /v2/product_mapping/set:
    post:
      operationId: set_product_mapping
      summary: Map a product to a line
      tags:
      - Product Mappings
      description: 'Map a Product to a Line - implying this Line can produce, or is producing this Product.


        If the supplied Product doesn''t exist, it will be created.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductMapping'
            examples:
              set by product ID and line ID:
                summary: Set product mapping with given product and line ID.
                value:
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  product:
                    id: b5da7b1f-3c16-5084-a5da-95b2eba5a4db
              set by product name and line name+factory:
                summary: Set product mapping with given product and line name  - alternative example.
                value:
                  line:
                    name: Line 01
                    factory:
                      id: e32d004e-ce8b-40bf-bbc1-14fd907d2f47
                  product:
                    name: 2AFBCA5E
      responses:
        '200':
          description: Successful response
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
components:
  responses:
    NotFoundError:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ParameterError:
      description: An error occurred regarding one of the input parameters
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - name
            - retryable
            properties:
              error:
                type: string
              name:
                type: string
              retryable:
                type: boolean
    UnauthorizedError:
      description: User has provided either no credentials or invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    NotUniqueError:
      description: 'A {match: "unique"} was requested, but multiple entities matched the search parameters.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - entity_name
            - num_matches
            - error
            - retryable
            properties:
              entity_name:
                type: string
              num_matches:
                type: integer
              error:
                type: string
              retryable:
                type: boolean
    UnimplementedError:
      description: Endpoint is not yet implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    InternalError:
      description: 'An internal server error has occurred. If reporting the error to Oden, include the ID returned in this response to aid in debugging.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - retryable
            - id
            properties:
              error:
                type: string
              retryable:
                type: boolean
              id:
                type: string
                format: uuid
  schemas:
    ProductMapping:
      type: object
      description: 'An entity representing a product/line mapping. Mappings are simple 1:1 relationships, and as such cannot be modified, only created.

        '
      properties:
        product:
          $ref: '#/components/schemas/Product'
        line:
          $ref: '#/components/schemas/Line'
        match:
          $ref: '#/components/schemas/Match'
    Factory:
      type: object
      description: An entity representing a factory.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type:
          - string
          - 'null'
        timezone:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    Line:
      type: object
      description: An entity representing a single line of production.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type: string
        factory:
          $ref: '#/components/schemas/Factory'
        match:
          $ref: '#/components/schemas/Match'
    Product:
      type: object
      description: An entity representing a product
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    GenericError:
      type: object
      required:
      - error
      - retryable
      properties:
        error:
          type: string
        retryable:
          type: boolean
    Match:
      type: string
      enum:
      - first
      - last
      - unique
      - all
      default: unique
      description: 'Describes which item(s) to match when searching for an entity:

        - `unique` (default): will return an error if the search object matches multiple entities

        - `all`: will return every item that matches search entity

        - `last`: will return the most recent object, where applicable

        - `first`: will return the least recent object, where applicable

        '
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Prefix the value with \"Token\" to indicate the custom authorization type
