openapi: 3.2.0
info:
  version: 2.0.0
  title: Oden Targets API
  contact:
    name: Oden Support
    email: support@oden.io
    url: https://oden.io/contact/
  description: The Oden Private Partner API exposes RESTful API endpoints for clients to get, create and update data on the Oden Platform.
servers:
- url: https://api.oden.app
  description: Oden API server
security:
- APIKeyAuth: []
tags:
- name: Targets
paths:
  /v2/target/search:
    post:
      operationId: search_targets
      summary: Search metric targets
      tags:
      - Targets
      description: 'Search for a Target by `line`, `metric_group`, and `product`. For each of these inputs, any of

        their unique indentifiers (as described in their `search` endpoint) may be used. See examples.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Target'
            examples:
              Search by for target product, line, and metric group:
                summary: Search for target by metric group, line, product
                value:
                  line:
                    id: 0012ab4d-1234-123a-8c76-6ea2344be6df
                  metric_group:
                    name: metric group name
                  product:
                    id: 0012ab4d-1234-123a-8c76-6ea2344be6df
      responses:
        '200':
          description: A list of targets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Target'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/target/set:
    post:
      operationId: set_target
      summary: Create or update a metric target
      tags:
      - Targets
      description: 'Create or update a Target.


        First the endpoint will search for a Target by `metric_group`, `product`, and `line`:

        - If the target does not exist a new target is created.

        - If the product or its mapping to the given line does not exist, they will be created.

        - If a target exists but with different parameters, it will be updated.

        - If the target exists with all the same parameters nothing is done.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Target'
            examples:
              set by product, line, and metric group:
                summary: Set target by metric group, line, product - each must be a valid search params.
                value:
                  line:
                    id: 0012ab4d-1234-123a-8c76-6ea2344be6df
                  metric_group:
                    name: metric group name
                  product:
                    id: 0012ab4d-1234-123a-8c76-6ea2344be6df
                  lsl: 100.0
                  target_value: 200
                  usl: 300.55
              set by product, line, and metric group II:
                summary: Set target by metric group, line, product - alternative example.
                value:
                  line:
                    name: line name (name only also requires factory)
                    factory:
                      id: 0012ab4d-1234-123a-8c76-6ea9904be6df
                  metric_group:
                    id: 0012ab4d-1234-123a-8c76-6ea9904be6df
                  product:
                    name: product name
                  lsl: 1
                  target_value: 2
                  usl: 3
      responses:
        '200':
          description: Updated target.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Target'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
components:
  responses:
    NotFoundError:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ParameterError:
      description: An error occurred regarding one of the input parameters
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - name
            - retryable
            properties:
              error:
                type: string
              name:
                type: string
              retryable:
                type: boolean
    UnauthorizedError:
      description: User has provided either no credentials or invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ForbiddenError:
      description: 'User has provided valid credentials but is not authorized to access the entity

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    NotUniqueError:
      description: 'A {match: "unique"} was requested, but multiple entities matched the search parameters.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - entity_name
            - num_matches
            - error
            - retryable
            properties:
              entity_name:
                type: string
              num_matches:
                type: integer
              error:
                type: string
              retryable:
                type: boolean
    UnimplementedError:
      description: Endpoint is not yet implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    InternalError:
      description: 'An internal server error has occurred. If reporting the error to Oden, include the ID returned in this response to aid in debugging.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - retryable
            - id
            properties:
              error:
                type: string
              retryable:
                type: boolean
              id:
                type: string
                format: uuid
  schemas:
    Factory:
      type: object
      description: An entity representing a factory.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type:
          - string
          - 'null'
        timezone:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    Line:
      type: object
      description: An entity representing a single line of production.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type: string
        factory:
          $ref: '#/components/schemas/Factory'
        match:
          $ref: '#/components/schemas/Match'
    Target:
      type: object
      description: An object representing a performance target for a line, product, and metric group.
      properties:
        metric_group:
          $ref: '#/components/schemas/MetricGroup'
        product:
          $ref: '#/components/schemas/Product'
        line:
          $ref: '#/components/schemas/Line'
        target_value:
          type: number
          format: double
        lsl:
          type: number
          format: double
        usl:
          type: number
          format: double
        match:
          $ref: '#/components/schemas/Match'
    Product:
      type: object
      description: An entity representing a product
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    GenericError:
      type: object
      required:
      - error
      - retryable
      properties:
        error:
          type: string
        retryable:
          type: boolean
    Match:
      type: string
      enum:
      - first
      - last
      - unique
      - all
      default: unique
      description: 'Describes which item(s) to match when searching for an entity:

        - `unique` (default): will return an error if the search object matches multiple entities

        - `all`: will return every item that matches search entity

        - `last`: will return the most recent object, where applicable

        - `first`: will return the least recent object, where applicable

        '
    MetricGroup:
      type: object
      description: An object representing a metric group; a grouping of like metrics across lines, factories.
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: string
          format: uuid
        unit_kind_of_quantity:
          type: string
        match:
          $ref: '#/components/schemas/Match'
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Prefix the value with \"Token\" to indicate the custom authorization type
