openapi: 3.2.0
info:
  version: 2.0.0
  title: Oden Intervals API
  contact:
    name: Oden Support
    email: support@oden.io
    url: https://oden.io/contact/
  description: The Oden Private Partner API exposes RESTful API endpoints for clients to get, create and update data on the Oden Platform.
servers:
- url: https://api.oden.app
  description: Oden API server
security:
- APIKeyAuth: []
tags:
- name: Intervals
paths:
  /v2/interval/search:
    post:
      operationId: search_intervals
      summary: Search intervals on a line
      tags:
      - Intervals
      description: 'Searches for intervals by `type`, `line` and other optional parameters:


        - `id` (for a specific Interval)

        - `match: unique` or omit


        OR


        - `match : last` for the most recent Interval of the given type on the given line


        OR


        - `start_time` and `end_time` (for a range of Intervals over a period of time)

        - `match: all` for more than one result


        OR


        - match all intervals for all lines in a given factory


        AND/OR


        - `name` (only for Intervals with a matching name)'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
            examples:
              Search for states on a line over a time period:
                summary: Search for states on a line over a time period
                value:
                  type:
                    name: STATE
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  start_time: '2021-04-04T08:00:04Z'
                  end_time: '2021-04-10T08:00:04Z'
                  match: all
              Search for an custom interval type interval:
                summary: Search for an operator id type interval
                value:
                  id: 1809d88adf0
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  type:
                    name: operator id
              Search for states on all lines in a given factory:
                summary: Search for states on all lines in a given factory
                value:
                  type:
                    name: STATE
                  line:
                    factory:
                      name: Factory A
                    match: all
                  start_time: '2021-04-04T08:00:04Z'
                  end_time: '2021-04-10T08:00:04Z'
                  match: all
      responses:
        '200':
          description: A list of intervals.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interval'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/interval/set:
    post:
      operationId: set_interval
      summary: Create or update an interval
      tags:
      - Intervals
      description: 'Create or update an Interval.


        Must include `line` and `type`. `match` must be omitted, `unique` or `last`


        - If `id` is not supplied, a new Interval will be created.


        - If `id` is supplied, existing Interval will be updated. This interval''s start time can be modified using `start_time` field.


        To update a specific interval supply the `id` of that interval.


        If the interval exists with all the same parameters nothing is done.


        To update the most recent Interval of a given `type` on a `line` one may use `match: last` and omit `id`


        For `RUN` type: if `product` and/or `product_mapping` does not exist a new one will be created. Further a `target`

        may be set by adding a `target` to the metadata field. The `line` and `product` for this target will be the same as the interval.


        Please see examples for more specific information.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
            examples:
              Create a Run, full schema:
                summary: Create a Run
                value:
                  type:
                    name: RUN
                  name: example_run
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                    name: Line 01
                    factory:
                      id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                      name: Factory A
                  start_time: '2021-04-04T08:00:04Z'
                  metadata:
                    product:
                      name: Example Product
              Create a Run, full schema, with target:
                summary: Create a Run with a target
                value:
                  type:
                    name: RUN
                  name: example_run
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                    name: Line 01
                    factory:
                      id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                      name: Factory A
                  start_time: '2021-04-04T08:00:04Z'
                  metadata:
                    product:
                      name: Example Product
                    target:
                      lsl: 1
                      target_value: 2
                      usl: 3
                      metric_group:
                        name: metric group name
              Create a Run, UUIDs only:
                summary: Create a Run - uuids only
                value:
                  type:
                    name: RUN
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  metadata:
                    product:
                      id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  start_time: '2021-04-04T08:00:04Z'
              Create a Run, names only:
                summary: Create a Run - names only
                value:
                  type:
                    name: RUN
                  line:
                    name: Line 01
                    factory:
                      name: Factory A
                  metadata:
                    product:
                      name: Example Product
                  start_time: '2021-04-04T08:00:04Z'
              Create a Batch:
                summary: Create a Batch
                value:
                  type:
                    name: BATCH
                  name: example_batch
                  line:
                    name: Line 01
                    factory:
                      name: Factory A
                  start_time: '2021-04-04T08:00:04Z'
              Update a custom interval type interval:
                summary: Update an operator id type interval
                value:
                  id: 1809d88adf0
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  name: updated_operator_id
                  type:
                    name: operator id
              Create a Run with a corresponding deletion example:
                summary: Create a Run with a corresponding deletion example
                value:
                  type:
                    name: RUN
                  name: deletable_run
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  start_time: '2021-04-04T08:00:04Z'
                  metadata:
                    product:
                      name: Example Product
              Create a State with a corresponding deletion example:
                summary: Create a State with a corresponding delete example
                value:
                  type:
                    name: STATE
                  name: deletable_state
                  line:
                    id: 4787d6fb-f01e-405b-a38d-db23e32fa0d1
                  start_time: '2021-04-04T08:00:04Z'
                  metadata:
                    category:
                      name: Planned Downtime
                    reason:
                      name: Preventive Maintenance
              Create a Batch with a corresponding deletion example:
                summary: Create a Batch with a corresponding deletion example
                value:
                  type:
                    name: BATCH
                  name: deletable_batch
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  start_time: '2021-04-04T08:00:04Z'
      responses:
        '200':
          description: Updated interval.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interval'
              examples:
                Set interval:
                  value:
                  - type:
                      id: 6f996655-4a3e-4b55-8121-724a4d14ca08
                    line:
                      id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                    name: example_interval
                    start_time: 2022-06-01 08:20:04+00:00
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
  /v2/interval/update:
    post:
      operationId: update_interval
      summary: Update an interval
      tags:
      - Intervals
      description: 'Update an existing Interval. This endpoint only updates intervals and will not create new ones.


        Must include `line`, `type`, and `id`. The `id` must reference an existing interval.


        This interval''s properties can be modified using the following fields:

        - `name`: Update the interval name

        - `start_time`: Modify the start time

        - `end_time`: Modify the end time

        - `metadata`: Update metadata (product, target, category, reason, etc.)


        If the interval does not exist, a 404 error will be returned.


        **Note:** The `id` must be obtained from either:

        - The response when creating an interval via `/v2/interval/set`

        - Searching for intervals via `/v2/interval/search`'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
            examples:
              Update a Run interval's product:
                summary: Update a Run interval with a new product
                value:
                  id: 178b9a1ec20
                  type:
                    name: RUN
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  metadata:
                    product:
                      name: Updated Product
              Update a Run interval with target:
                summary: Update a Run interval with a new target
                value:
                  id: 178b9a1ec20
                  type:
                    name: RUN
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  metadata:
                    product:
                      name: Example Product
                    target:
                      lsl: 1
                      target_value: 2
                      usl: 3
                      metric_group:
                        name: metric group name
              Update a custom interval:
                summary: Update a custom interval type's name and time
                value:
                  id: 1809d88adf0
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  name: updated_operator_id
                  type:
                    name: operator id
                  start_time: '2021-04-04T09:00:04Z'
              Update a State interval:
                summary: Update a State interval's category and reason
                value:
                  id: 178a61c0f00
                  type:
                    name: STATE
                  line:
                    id: 4787d6fb-f01e-405b-a38d-db23e32fa0d1
                  metadata:
                    category:
                      name: Unplanned Downtime
                    reason:
                      name: Equipment Failure
              Update a Batch interval:
                summary: Update a Batch interval's name
                value:
                  id: 178b9a1ec20
                  type:
                    name: BATCH
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  name: updated_batch_name
      responses:
        '200':
          description: Updated interval.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interval'
        '400':
          $ref: '#/components/responses/ParameterError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
  /v2/interval/delete:
    post:
      operationId: delete_interval
      summary: Delete an interval
      tags:
      - Intervals
      description: 'Delete an interval by `type`, `line`, and `id`


        **Note:** The `id` must be obtained from either:

        - The response when creating an interval via `/v2/interval/set`

        - Searching for intervals via `/v2/interval/search`


        The examples below use placeholder IDs - replace with actual IDs from your system.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
            examples:
              Delete a Run interval by ID:
                summary: Delete a Run interval by ID (replace with actual ID)
                value:
                  id: <REPLACE_WITH_ACTUAL_RUN_UUID>
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  type:
                    name: RUN
              Delete a State interval by ID:
                summary: Delete a State type interval by ID (replace with actual ID)
                value:
                  id: <REPLACE_WITH_ACTUAL_STATE_ID>
                  line:
                    id: 4787d6fb-f01e-405b-a38d-db23e32fa0d1
                  type:
                    name: STATE
              Delete a Batch interval by ID:
                summary: Delete a Batch type interval by ID (replace with actual ID)
                value:
                  id: <REPLACE_WITH_ACTUAL_BATCH_UUID>
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  type:
                    name: BATCH
              Delete a custom interval:
                summary: Delete an "operator id" type interval
                value:
                  id: 1809d88adf0
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  type:
                    name: operator id
      responses:
        '200':
          description: A list containing the deleted interval.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interval'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/intervals/set:
    post:
      operationId: bulk_set_intervals
      summary: Create a set of intervals
      tags:
      - Intervals
      description: 'Create (Does not update) a group of custom intervals, for the same `type` and `line`.

        Line and type do not need to be included in each individual interval, just once at the top level.


        Limitations:

        - Cannot excees 2500 intervals per request.

        - Will not write over other intervals

        - Does not support "batch", "run", or "state" interval types.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntervalBulkCreate'
            examples:
              Create a set of intervals:
                summary: Create a set of intervals
                value:
                  type:
                    name: operator id
                  line:
                    name: Line 01
                    factory:
                      name: Factory A
                  intervals:
                  - start_time: '2021-04-04T08:00:04Z'
                    end_time: '2021-04-04T08:30:04Z'
                    name: Example Value
                  - start_time: '2021-04-04T09:00:04Z'
                    end_time: '2021-04-04T09:30:04Z'
                    name: Example Value 2
      responses:
        '200':
          description: A list of created interval IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          $ref: '#/components/responses/ParameterError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
  /v2/intervals/update:
    post:
      operationId: bulk_update_intervals
      summary: Update a set of intervals
      tags:
      - Intervals
      description: 'Update multiple existing intervals. This endpoint only updates intervals and will not create new ones.


        Each interval in the `intervals` array must include an `id` that references an existing interval.


        Updatable fields for each interval:

        - `name`: Update the interval name

        - `start_time`: Modify the start time

        - `end_time`: Modify the end time

        - `metadata`: Update metadata (product, target, category, reason, etc.)


        The endpoint will attempt to update all intervals and return information about successes and failures:

        - Successfully updated intervals are returned in the response

        - Failed intervals are listed with their IDs and error reasons


        Limitations:

        - Cannot exceed 2500 intervals per request

        - All intervals must be of the same `type` and on the same `line`


        **Note:** Interval IDs must be obtained from either:

        - The response when creating intervals via `/v2/interval/set` or `/v2/intervals/set`

        - Searching for intervals via `/v2/interval/search`'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntervalBulkUpdate'
            examples:
              Update multiple custom intervals:
                summary: Update a set of custom intervals
                value:
                  type:
                    name: operator id
                  line:
                    id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  intervals:
                  - id: 1809d88adf0
                    name: updated_operator_1
                    start_time: '2021-04-04T08:00:04Z'
                    end_time: '2021-04-04T08:30:04Z'
                  - id: 1809d88adf1
                    name: updated_operator_2
                    start_time: '2021-04-04T09:00:04Z'
                    end_time: '2021-04-04T09:30:04Z'
              Update multiple State intervals:
                summary: Update multiple State intervals with new categories
                value:
                  type:
                    name: STATE
                  line:
                    name: Line 01
                    factory:
                      name: Factory A
                  intervals:
                  - id: 178a61c0f00
                    metadata:
                      category:
                        name: Unplanned Downtime
                      reason:
                        name: Equipment Failure
                  - id: 178a61c0f01
                    metadata:
                      category:
                        name: Planned Downtime
                      reason:
                        name: Preventive Maintenance
      responses:
        '200':
          description: Response containing successfully updated intervals and any failures that occurred.
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_updated:
                    type: integer
                  updated_intervals:
                    type: array
                    items:
                      $ref: '#/components/schemas/Interval'
                  num_failed:
                    type: integer
                  failed_intervals:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        error:
                          type: string
        '400':
          $ref: '#/components/responses/ParameterError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
  /v2/intervals/delete:
    post:
      operationId: bulk_delete_intervals
      summary: Delete intervals in a time range
      tags:
      - Intervals
      description: 'Delete a group of intervals by a single `type` and a single `line`, between `start_time` and `end_time`. Returns a list of intervals that were not deleted, and the number of intervals deleted.


        Limitations:

        - Cannot exceed 15,000 intervals per request, or 30 days worth of data.

        - Currently does not support "batch" or "run" interval types.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntervalBulkDelete'
            examples:
              Delete a set of intervals:
                summary: Delete a set of intervals in range
                value:
                  line:
                    name: Line 01
                    factory:
                      name: Factory A
                  type:
                    name: operator id
                  start_time: '2021-04-04T08:00:04Z'
                  end_time: '2021-04-10T08:00:04Z'
      responses:
        '200':
          description: A list containing any intervals found but not deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_deleted:
                    type: integer
                  failed_intervals:
                    type: array
                    items:
                      type: string
        '400':
          $ref: '#/components/responses/ParameterError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
  /v2/interval_type/search:
    post:
      operationId: search_interval_types
      summary: Search interval types
      tags:
      - Intervals
      description: 'Search for Interval Types by `name`, `id`, or just `match: all` to return all Interval Types associated with the your organization.

        Basic Interval Types -- `RUN`, `BATCH`, and `STATE` -- are dedicated interval types that come out-of-the-box with Oden.

        Custom Interval Types may be created by users.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntervalType'
            examples:
              Search for all interval types:
                summary: Search for all interval types.
                value:
                  match: all
              Search for interval type by name:
                summary: Search for all interval types.
                value:
                  name: operator id
                  match: unique
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IntervalType'
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/interval_type/set:
    post:
      operationId: set_interval_type
      summary: Create or update a custom interval type
      tags:
      - Intervals
      description: '**Create** (no `id` in the body): send `name` (required) and optional `metadata_schema` / `tags`.


        **Update** (with `id`): send the interval type’s `id` and optional `metadata_schema` / `tags` only. Do not send `name` for updates; including `name` returns 400. Renames are not supported.


        **Patch (update only)**: `metadata_schema` — if the key is missing, the existing value is kept; if present, it replaces. `tags` — if the key is missing, tags are unchanged; `null` leaves tags unchanged; `[]` clears tags; a non-empty array replaces.


        **Built-in types (RUN, BATCH, STATE) cannot be created, set, or deleted.**'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntervalTypeSet'
            examples:
              create:
                summary: Create a custom interval type
                value:
                  name: operator id
              update by id (metadata and tags only):
                summary: Update an existing type by id
                value:
                  id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
                  metadata_schema: '{"type":"object"}'
                  tags:
                  - a
      responses:
        '200':
          description: The interval type after set.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntervalType'
        '400':
          $ref: '#/components/responses/ParameterError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
  /v2/interval_type/delete:
    post:
      operationId: delete_interval_type
      summary: Delete a custom interval type
      tags:
      - Intervals
      description: Delete an existing custom Interval Type. `id` is required. Built-in types (RUN, BATCH, STATE) cannot be deleted.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntervalType'
            examples:
              Delete a custom interval type by id:
                summary: Delete a custom interval type by id
                value:
                  id: 2fc8b5e5-fb88-48a7-9c35-4a763206608c
      responses:
        '200':
          description: The deleted interval type.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntervalType'
        '400':
          $ref: '#/components/responses/ParameterError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
components:
  schemas:
    StateReason:
      type: object
      description: An entity representing a state reason. During search, ID will take precedence over name.
      properties:
        id:
          type: integer
        name:
          type: string
    IntervalBulkDelete:
      type: object
      description: A range of intervals to delete
      properties:
        type:
          $ref: '#/components/schemas/IntervalType'
        line:
          $ref: '#/components/schemas/Line'
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        hard_delete:
          type: boolean
          default: true
    Line:
      type: object
      description: An entity representing a single line of production.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type: string
        factory:
          $ref: '#/components/schemas/Factory'
        match:
          $ref: '#/components/schemas/Match'
    GenericError:
      type: object
      required:
      - error
      - retryable
      properties:
        error:
          type: string
        retryable:
          type: boolean
    BatchMetadata:
      type: object
      description: Metadata associated with a batch interval
      properties:
        metadata_type:
          type: string
          enum:
          - batch
          readOnly: true
          x-go-type-skip-optional-pointer: true
        run:
          $ref: '#/components/schemas/Interval'
      additionalProperties: true
    Match:
      type: string
      enum:
      - first
      - last
      - unique
      - all
      default: unique
      description: 'Describes which item(s) to match when searching for an entity:

        - `unique` (default): will return an error if the search object matches multiple entities

        - `all`: will return every item that matches search entity

        - `last`: will return the most recent object, where applicable

        - `first`: will return the least recent object, where applicable

        '
    IntervalTypeSet:
      type: object
      description: 'Create or update a custom interval type. Omit `id` to create (requires `name`);

        include `id` to update. On update, `name` (if present) is ignored. Use `null` for `tags` to leave tags unchanged; `[]` clears tags.

        '
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        metadata_schema:
          type: string
        tags:
          type:
          - array
          - 'null'
          items:
            type: string
    Interval:
      type: object
      description: An object representing an interval of time on a line and associated metadata.
      required:
      - type
      - line
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/IntervalType'
        name:
          type: string
        line:
          $ref: '#/components/schemas/Line'
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        metadata:
          description: 'Metadata about this interval, such as the associated run or the state category. Will differ based on the type of interval.

            '
          oneOf:
          - $ref: '#/components/schemas/BatchMetadata'
          - $ref: '#/components/schemas/RunMetadata'
          - $ref: '#/components/schemas/StateMetadata'
          - $ref: '#/components/schemas/CustomMetadata'
          discriminator:
            propertyName: metadata_type
            mapping:
              batch: '#/components/schemas/BatchMetadata'
              run: '#/components/schemas/RunMetadata'
              state: '#/components/schemas/StateMetadata'
              custom: '#/components/schemas/CustomMetadata'
        match:
          $ref: '#/components/schemas/Match'
    RunMetadata:
      type: object
      description: Metadata associated with a run interval
      properties:
        metadata_type:
          type: string
          enum:
          - run
          readOnly: true
          x-go-type-skip-optional-pointer: true
        product:
          $ref: '#/components/schemas/Product'
        target:
          $ref: '#/components/schemas/Target'
      additionalProperties: true
    StateMetadata:
      type: object
      description: Metadata associated with a state interval
      properties:
        metadata_type:
          type: string
          enum:
          - state
          readOnly: true
          x-go-type-skip-optional-pointer: true
        reason:
          $ref: '#/components/schemas/StateReason'
        comment:
          type: string
        category:
          $ref: '#/components/schemas/StateCategory'
      additionalProperties: true
    CustomMetadata:
      type: object
      description: Metadata associated with a custom interval type
      properties:
        metadata_type:
          type: string
          enum:
          - custom
          readOnly: true
          x-go-type-skip-optional-pointer: true
      additionalProperties: true
    IntervalType:
      type: object
      description: An object representing a interval type.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    Target:
      type: object
      description: An object representing a performance target for a line, product, and metric group.
      properties:
        metric_group:
          $ref: '#/components/schemas/MetricGroup'
        product:
          $ref: '#/components/schemas/Product'
        line:
          $ref: '#/components/schemas/Line'
        target_value:
          type: number
          format: double
        lsl:
          type: number
          format: double
        usl:
          type: number
          format: double
        match:
          $ref: '#/components/schemas/Match'
    IntervalBulkCreate:
      type: object
      description: A set of intervals to create
      properties:
        type:
          $ref: '#/components/schemas/IntervalType'
        line:
          $ref: '#/components/schemas/Line'
        intervals:
          type: array
          items:
            $ref: '#/components/schemas/Interval'
    MetricGroup:
      type: object
      description: An object representing a metric group; a grouping of like metrics across lines, factories.
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: string
          format: uuid
        unit_kind_of_quantity:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    IntervalBulkUpdate:
      type: object
      description: A set of intervals to update
      properties:
        type:
          $ref: '#/components/schemas/IntervalType'
        line:
          $ref: '#/components/schemas/Line'
        intervals:
          type: array
          items:
            $ref: '#/components/schemas/Interval'
    Factory:
      type: object
      description: An entity representing a factory.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type:
          - string
          - 'null'
        timezone:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    StateCategory:
      type: object
      description: An entity representing a state category. During search, ID will take precedence over name.
      properties:
        id:
          type: integer
        name:
          type: string
    Product:
      type: object
      description: An entity representing a product
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        match:
          $ref: '#/components/schemas/Match'
  responses:
    InternalError:
      description: 'An internal server error has occurred. If reporting the error to Oden, include the ID returned in this response to aid in debugging.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - retryable
            - id
            properties:
              error:
                type: string
              retryable:
                type: boolean
              id:
                type: string
                format: uuid
    NotFoundError:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ForbiddenError:
      description: 'User has provided valid credentials but is not authorized to access the entity

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    UnimplementedError:
      description: Endpoint is not yet implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ParameterError:
      description: An error occurred regarding one of the input parameters
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - name
            - retryable
            properties:
              error:
                type: string
              name:
                type: string
              retryable:
                type: boolean
    UnauthorizedError:
      description: User has provided either no credentials or invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    NotUniqueError:
      description: 'A {match: "unique"} was requested, but multiple entities matched the search parameters.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - entity_name
            - num_matches
            - error
            - retryable
            properties:
              entity_name:
                type: string
              num_matches:
                type: integer
              error:
                type: string
              retryable:
                type: boolean
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Prefix the value with \"Token\" to indicate the custom authorization type
