openapi: 3.2.0
info:
  version: 2.0.0
  title: Oden Quality Test API
  contact:
    name: Oden Support
    email: support@oden.io
    url: https://oden.io/contact/
  description: The Oden Private Partner API exposes RESTful API endpoints for clients to get, create and update data on the Oden Platform.
servers:
- url: https://api.oden.app
  description: Oden API server
security:
- APIKeyAuth: []
tags:
- name: Quality Test
paths:
  /v2/quality_test/set:
    post:
      operationId: set_quality_test
      summary: Create or update a quality test result
      tags:
      - Quality Test
      description: 'Create or update a Quality Test record:

        - To update `id` must be supplied. Only the supplied fields will be updated, the rest will remain unchanged.

        - If `id` is not supplied, a new `quality_test_record` will be created.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityTest'
            examples:
              Create quality test record:
                summary: Create quality test record.
                value:
                  interval:
                    id: 178a61c0f00
                    line:
                      factory:
                        id: e32d004e-ce8b-40bf-bbc1-14fd907d2f47
                      name: Line 01
                    type:
                      id: e07da9a8-f2fd-480c-a315-d4c84fcac08c
                      name: BATCH
                  quality_schema:
                    id: '66'
                  raw_data:
                    fdr: test string 3
                    impedance: 6.789
                    test_length: 10
                    test_rl: test string
                  timestamp: '2022-02-18T16:28:04Z'
      responses:
        '200':
          description: Successful response
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/quality_test/search:
    post:
      operationId: search_quality_tests
      summary: Search quality tests
      tags:
      - Quality Test
      description: 'Searches for Quality Test[s] by:


        - `id`


        OR


        - `interval` (of type `RUN` or `BATCH`)'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityTest'
            examples:
              Search quality test by id:
                summary: Use test ID to identify quality test.
                value:
                  id: 16a8fa1f-ba0a-4040-81c9-ac4dd054bdbb
                  match: unique
              Search quality test by interval:
                summary: Use BATCH interval to identify quality tests.
                value:
                  interval:
                    name: example-batch-interval
                    line:
                      name: Line 01
                      factory:
                        name: Factory A
                    type:
                      name: BATCH
                  match: all
      responses:
        '200':
          description: Successful response
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/quality_test/delete:
    post:
      operationId: delete_quality_test
      summary: Delete a quality test
      tags:
      - Quality Test
      description: 'Searches for uniqueQuality Test by:


        - `id`


        OR


        - `interval` (of type `RUN` or `BATCH`)*


        *This only work if there is a single quality test record for the interval.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityTest'
            examples:
              Delete quality test by id:
                summary: Use test ID to identify quality test.
                value:
                  id: 16a8fa1f-ba0a-4040-81c9-ac4dd054bdbb
                  match: unique
      responses:
        '200':
          description: Successful response
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/quality_tests/delete:
    post:
      operationId: bulk_delete_quality_tests
      summary: Delete multiple quality tests
      tags:
      - Quality Test
      description: 'Bulk deletes quality tests, either:

        - All quality tests on a given `line` whose `timsetamp` is between `start_time` and `end_time`

        OR

        - All quality tests whose `id` is supplied


        It will do one or the other, with a bias for `id`''s if both are supplied.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                    format: uuid
                line:
                  $ref: '#/components/schemas/Line'
                start_time:
                  type: string
                  format: date-time
                end_time:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Successful response
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /v2/quality_schema/search:
    post:
      operationId: search_quality_schemas
      summary: Search quality schemas for a factory
      tags:
      - Quality Test
      description: 'Searches for Quality Schema[s] by:


        - `factory`'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualitySchema'
            examples:
              Get all quality schemas for Factory A:
                summary: Get all quality schemas for Factory A.
                value:
                  factory:
                    name: Factory A
      responses:
        '200':
          description: Successful response
        '409':
          $ref: '#/components/responses/NotUniqueError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/UnimplementedError'
        '400':
          $ref: '#/components/responses/ParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    StateReason:
      type: object
      description: An entity representing a state reason. During search, ID will take precedence over name.
      properties:
        id:
          type: integer
        name:
          type: string
    Line:
      type: object
      description: An entity representing a single line of production.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type: string
        factory:
          $ref: '#/components/schemas/Factory'
        match:
          $ref: '#/components/schemas/Match'
    QualitySchema:
      type: object
      description: 'A schema for quality tests. Note: the id is currently implemented as a string, but that string should be a stringified integer.

        '
      properties:
        id:
          type: string
          example: '23'
        factory:
          $ref: '#/components/schemas/Factory'
        schema:
          type: string
          format: json
        description:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    GenericError:
      type: object
      required:
      - error
      - retryable
      properties:
        error:
          type: string
        retryable:
          type: boolean
    Match:
      type: string
      enum:
      - first
      - last
      - unique
      - all
      default: unique
      description: 'Describes which item(s) to match when searching for an entity:

        - `unique` (default): will return an error if the search object matches multiple entities

        - `all`: will return every item that matches search entity

        - `last`: will return the most recent object, where applicable

        - `first`: will return the least recent object, where applicable

        '
    BatchMetadata:
      type: object
      description: Metadata associated with a batch interval
      properties:
        metadata_type:
          type: string
          enum:
          - batch
          readOnly: true
          x-go-type-skip-optional-pointer: true
        run:
          $ref: '#/components/schemas/Interval'
      additionalProperties: true
    Interval:
      type: object
      description: An object representing an interval of time on a line and associated metadata.
      required:
      - type
      - line
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/IntervalType'
        name:
          type: string
        line:
          $ref: '#/components/schemas/Line'
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        metadata:
          description: 'Metadata about this interval, such as the associated run or the state category. Will differ based on the type of interval.

            '
          oneOf:
          - $ref: '#/components/schemas/BatchMetadata'
          - $ref: '#/components/schemas/RunMetadata'
          - $ref: '#/components/schemas/StateMetadata'
          - $ref: '#/components/schemas/CustomMetadata'
          discriminator:
            propertyName: metadata_type
            mapping:
              batch: '#/components/schemas/BatchMetadata'
              run: '#/components/schemas/RunMetadata'
              state: '#/components/schemas/StateMetadata'
              custom: '#/components/schemas/CustomMetadata'
        match:
          $ref: '#/components/schemas/Match'
    RunMetadata:
      type: object
      description: Metadata associated with a run interval
      properties:
        metadata_type:
          type: string
          enum:
          - run
          readOnly: true
          x-go-type-skip-optional-pointer: true
        product:
          $ref: '#/components/schemas/Product'
        target:
          $ref: '#/components/schemas/Target'
      additionalProperties: true
    StateMetadata:
      type: object
      description: Metadata associated with a state interval
      properties:
        metadata_type:
          type: string
          enum:
          - state
          readOnly: true
          x-go-type-skip-optional-pointer: true
        reason:
          $ref: '#/components/schemas/StateReason'
        comment:
          type: string
        category:
          $ref: '#/components/schemas/StateCategory'
      additionalProperties: true
    CustomMetadata:
      type: object
      description: Metadata associated with a custom interval type
      properties:
        metadata_type:
          type: string
          enum:
          - custom
          readOnly: true
          x-go-type-skip-optional-pointer: true
      additionalProperties: true
    IntervalType:
      type: object
      description: An object representing a interval type.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    Target:
      type: object
      description: An object representing a performance target for a line, product, and metric group.
      properties:
        metric_group:
          $ref: '#/components/schemas/MetricGroup'
        product:
          $ref: '#/components/schemas/Product'
        line:
          $ref: '#/components/schemas/Line'
        target_value:
          type: number
          format: double
        lsl:
          type: number
          format: double
        usl:
          type: number
          format: double
        match:
          $ref: '#/components/schemas/Match'
    MetricGroup:
      type: object
      description: An object representing a metric group; a grouping of like metrics across lines, factories.
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: string
          format: uuid
        unit_kind_of_quantity:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    Factory:
      type: object
      description: An entity representing a factory.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        secondary_name:
          type:
          - string
          - 'null'
        timezone:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    StateCategory:
      type: object
      description: An entity representing a state category. During search, ID will take precedence over name.
      properties:
        id:
          type: integer
        name:
          type: string
    Product:
      type: object
      description: An entity representing a product
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        match:
          $ref: '#/components/schemas/Match'
    QualityTest:
      type: object
      description: 'An object representing a QA test for a line for a particular run or batch interval.

        '
      properties:
        id:
          type: string
          format: uuid
        raw_data:
          type: object
        timestamp:
          type: string
          format: date-time
        interval:
          $ref: '#/components/schemas/Interval'
        quality_schema:
          $ref: '#/components/schemas/QualitySchema'
        match:
          $ref: '#/components/schemas/Match'
  responses:
    InternalError:
      description: 'An internal server error has occurred. If reporting the error to Oden, include the ID returned in this response to aid in debugging.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - retryable
            - id
            properties:
              error:
                type: string
              retryable:
                type: boolean
              id:
                type: string
                format: uuid
    NotFoundError:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ForbiddenError:
      description: 'User has provided valid credentials but is not authorized to access the entity

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    UnimplementedError:
      description: Endpoint is not yet implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    ParameterError:
      description: An error occurred regarding one of the input parameters
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            - name
            - retryable
            properties:
              error:
                type: string
              name:
                type: string
              retryable:
                type: boolean
    UnauthorizedError:
      description: User has provided either no credentials or invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    NotUniqueError:
      description: 'A {match: "unique"} was requested, but multiple entities matched the search parameters.

        '
      content:
        application/json:
          schema:
            type: object
            required:
            - entity_name
            - num_matches
            - error
            - retryable
            properties:
              entity_name:
                type: string
              num_matches:
                type: integer
              error:
                type: string
              retryable:
                type: boolean
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Prefix the value with \"Token\" to indicate the custom authorization type
